### ISSUE TITLE
Question about trgsw

### ISSUE THREAD

**Issue by kenmaro3** [virtualsecureplatform/TFHEpp#36]
日本語で書きます、失礼します。
一つ質問させてください。

test/externalproduct.cpp
等でexternalproduct を行う時、
あえてゼロの暗号文でマスクをせず、平文をそのまま掛け算しようとしています。

```trgsw.cpp
template <class P>
TRGSW<P> trgswSymEncrypt(const Polynomial<P> &p, const double alpha,
                         const Key<P> &key)
{
    constexpr std::array<typename P::T, P::l> h = hgen<P>();

    TRGSW<P> trgsw;
    for (TRLWE<P> &trlwe : trgsw) trlwe = trlweSymEncryptZero<P>(alpha, key); <=== ここをコメントアウト
    for (int i = 0; i < P::l; i++) {
        for (int j = 0; j < P::n; j++) {
            trgsw[i][0][j] += static_cast<typename P::T>(p[j]) * h[i]; <=== ここを += から　= に変更
            trgsw[i + P::l][1][j] += static_cast<typename P::T>(p[j]) * h[i]; 　<=== ここを += から　= に変更
        }
    }
    return trgsw;
}
```

として、平文を基数展開したものをFakeの（平文の）GSWとして、
externalproduct を test/externalproduct.cpp と同じ要領で掛け算し、
結果のtrlweを復号しようとすると、思った値と異なる値が出ているのですが、
なにか間違ったことをしているでしょうか、、？

結果のリプロデュースは

https://github.com/kenmaro3/TFHEpp/tree/mult-const

ここで　./tutorial/mytest8
で可能です。

もし可能でしたらご回答いただけると嬉しいです！

**Comment by nindanaoto** [comment]
たぶんtrgswが0初期化されていないだけな気がします。
平文がわかっているならTRLWEをそのまま定数倍したほうがDecompositonによるノイズがなくなるので望ましいと思います。

**Comment by kenmaro3** [comment]
@nindanaoto 
ゼロ初期化されていないかもということ、了解しました、ゼロを明示的に入れて試してみます。

アドバイスもいただきありがとうございます！！

**Comment by kenmaro3** [comment]
@nindanaoto 
ご指摘の通り初期化をするとうまくいきました、、！
ありがとうございました。クローズさせていただきます。
