### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by shiuannnnn** [virtualsecureplatform/TFHEpp#39]
Hi, everyone!
Does anyone know the reason why I completely "make" and then execute the /test/nand but it says the segmentation fault error?
I have tried in both ubuntu-20.04 and centos-7.8, but give the same error result...
Thanks for the reading.
![image](https://user-images.githubusercontent.com/88835726/190565722-be0f362b-79fb-4063-be92-0e5594da1f40.png)

**Comment by prajyotgupta** [comment]
Hi! 
I'm receiving the exact same issue, with all the tests including nand ,tlwe etc. Do we need to update any test files to resolve this?

**Comment by shiuannnnn** [comment]
Hi, I'm still not sure about this problem...
Maybe you can go to try the openFHE or concrete if you want to find another TFHE-based open source.

**Comment by nindanaoto** [comment]
You need 
```
ulimit -s unlimited
```
To run the test because of large use of stacks. I'll add it to README.md.

**Comment by ushitora-anqou** [comment]
By the way, this issue is due to the large size of the bootstrapping key (as far as I know). We maybe should avoid this on the library's side, rather than write it down on the document.

**Comment by nindanaoto** [comment]
This issue is resolved. (No need for `ulimit -s unlimited` in current master branch.)
