### ISSUE TITLE
Different parameter call between verify.cpp(cloud.cpp) and tlwe.hpp(gate.hpp) causes error

### ISSUE THREAD

**Issue by shiuannnnn** [virtualsecureplatform/TFHEpp#41]
Hello,

I'm trying to run the tutorial test but the error occurred. (the picture below shows the problem)

Does anyone know the reason for the different parameter call?

To my knowledge, lvl0param is for the LWE ciphertext and lvl1param is for the RLWE. (TBC)
Besides, it seems that the [Yao's Millionaires' problem](https://en.wikipedia.org/wiki/Yao%27s_Millionaires%27_problem) in the "tutorial" is solved in gate level, so we need the gate bootstrapping like HomXOR, HomAND...

So, I'm wondering why the params declared in tlwe.hpp(gate.hpp) is lvl1param rather than lvl0param?

![image](https://user-images.githubusercontent.com/88835726/205480825-e2b8f7c7-c3bc-4c73-b230-1090349c18c0.png)

To fix this error, I had tried either change the related files to lvl0param or to lvl1param to make sure the dimension are same. However, the original error would fix but result in another issue.

Thanks for the reading and hope I can learn from anyone of you!

**Comment by nindanaoto** [comment]
Oh, I'm a bit sorry about this because this tutorial is currently out-dated...... Not following some API changes in latest codes. 
I'll fix it.

**Comment by nindanaoto** [comment]
I finally fixed this issue. Now it can work.
