### ISSUE TITLE
tlwemult and trlwemult test not passed

### ISSUE THREAD

**Issue by Farheen-github** [virtualsecureplatform/TFHEpp#47]
Hi 
I am working on multiplication of polynomials and when I run these two files, in the test dir, tlwemult.cpp and trlwemult.cpp
This error comes up, it never truly equates the answer
<img width="1287" alt="Screen Shot 2023-10-31 at 1 23 03 PM" src="https://github.com/virtualsecureplatform/TFHEpp/assets/53074806/b741b88d-3198-46af-9539-341b0d195e40">

**Comment by nindanaoto** [comment]
Hi,
tlwemult and trlwemult is the experimental feature, so it is not a severe issue. However, CI is missing to catch this test failure. It is a serious issue, so I will fix it. 
Anyway, the cause of this failure comes from incorrect parameter selection. The parameter cannot afford the error growth by the multiplication. I'm not sure about what you want, but BFV functionality supported in this library is very limited, I guess that only two or a bit more is the maximum limit of multiplication depth. This comes from that TFHEpp currently supports only 64bit modulus at the maximum. Maybe further integration with Intel HEXL is needed for a larger modulus. 
The other way to do polynomial multiplication which can be easily integrated with TFHE is to use TRGSW to encrypt the polynomial, but currently, there is no test for that.

**Comment by nindanaoto** [comment]
@Farheen-github 
I fixed the issue. I found that Δ is set to an incorrect value (divided by two) in the parameter. Please retry with the master brunch.
